# Generated by Django 5.1.6 on 2025-04-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='daten',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='date',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_saves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.news')),
            ],
        ),
    ]
