# Generated by Django 5.1.6 on 2025-04-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_news_daten_alter_newscategory_date_saves'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saves',
            unique_together={('user_id', 'user_saves')},
        ),
    ]
